// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaWK6WuCt7UCAfGQX7JJ2fPk2X6W23LAQ',
    appId: '1:72419158941:web:e890b0669585053480dd74',
    messagingSenderId: '72419158941',
    projectId: 'slumber-ee7ce',
    authDomain: 'slumber-ee7ce.firebaseapp.com',
    storageBucket: 'slumber-ee7ce.firebasestorage.app',
    measurementId: 'G-1MER3JKVV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8SyWFW5IVY0H3f80l5RsZt9S6A8qISvg',
    appId: '1:72419158941:android:d886b9091f44152980dd74',
    messagingSenderId: '72419158941',
    projectId: 'slumber-ee7ce',
    storageBucket: 'slumber-ee7ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_n__ZF-rjZjn-seP-rtX96j_QDdl9HNU',
    appId: '1:72419158941:ios:f109df103a2aa22c80dd74',
    messagingSenderId: '72419158941',
    projectId: 'slumber-ee7ce',
    storageBucket: 'slumber-ee7ce.firebasestorage.app',
    iosClientId: '72419158941-gdi03ili6o9kif9paoha6p7ssotv8jd0.apps.googleusercontent.com',
    iosBundleId: 'com.example.slumber',
  );
}
